version: '3'
services:
    api:
        build: 'techflix-api'
        ports:
            - "8080:8080"
        env_file:
            - docker.env
        depends_on: 
            - library
            - metadata
            - ratings
    library:
        build: 'library-service'
        ports:
            - "8000:3000"
    metadata:
        build: 'metadata-service'
        ports:
            - "8001:3000"
        env_file: 
            - docker.env
            - docker-secret.env
    ratings:
        build: 'ratings-service'
        ports:
            - "8002:3000"
        env_file: 
            - docker.env
            - docker-secret.env
    ui:
        build: 'techflix-ui'
        ports:
            - "3000:3000"
        env_file:
            - docker.env
        depends_on: 
            - api
    player:
        build: 'techflix-player'
        ports:
            - "3001:3000"
        env_file:
            - docker.env
        depends_on: 
            - api