version: '3'
services:
    api:
        build: 'techflix-api'
        ports:
            - "8080:8080"
        depends_on: 
            - library
            - reviews
    library:
        build: 'library-service'
        ports:
            - "8000:3000"
    reviews:
        build: 'reviews-service'
        ports:
            - "8001:3000"
        env_file: 
            - docker.env
    ui:
        build: 'techflix-ui'
        ports:
            - "3000:3000"
        depends_on: 
            - api
    player:
        build: 'techflix-player'
        ports:
            - "3001:3000"
        depends_on: 
            - api